local M = {}

local c = require("2017dark.colors").get_colors()

function M.colorscheme()
	vim.cmd("highlight clear")
	vim.cmd("syntax reset")

	vim.o.background = "dark"
	vim.g.termguicolors = true
	vim.g.colors_name = "2017dark"

	local hl = vim.api.nvim_set_hl
	local isDark = vim.o.background == "dark"
	hl(0, "Normal", { fg = c.vscFront, bg = c.vscBack })
	hl(0, "ColorColumn", { fg = "NONE", bg = c.vscCursorDarkDark })
	hl(0, "Cursor", { fg = c.vscCursorDark, bg = c.vscCursorLight })
	hl(0, "CursorLine", { bg = c.vscCursorLineWhite })
	hl(0, "CursorColumn", { fg = "NONE", bg = c.vscCursorDarkDark })
	hl(0, "Directory", { fg = c.vscBlue, bg = c.vscBack })
	hl(0, "DiffAdd", { fg = "NONE", bg = c.vscDiffGreenLight })
	hl(0, "DiffChange", { fg = "NONE", bg = c.vscDiffRedDark })
	hl(0, "DiffDelete", { fg = "NONE", bg = c.vscDiffRedLight })
	hl(0, "DiffText", { fg = "NONE", bg = c.vscDiffRedLight })
	hl(0, "EndOfBuffer", { fg = c.vscBack, bg = "NONE" })
	hl(0, "ErrorMsg", { fg = c.vscRed, bg = c.vscBack })
	hl(0, "VertSplit", { fg = c.vscSplitDark, bg = c.vscBack })
	hl(0, "WinSeparator", { link = "VertSplit" })
	hl(0, "Folded", { fg = "NONE", bg = c.vscFoldBackground })
	hl(0, "FoldColumn", { fg = c.vscLineNumber, bg = c.vscBack })
	hl(0, "SignColumn", { fg = "NONE", bg = c.vscBack })
	hl(0, "IncSearch", { fg = c.vscNone, bg = c.vscSearchCurrent })
	hl(0, "LineNr", { fg = c.vscWhite, bg = c.vscBack })
	hl(0, "CursorLineNr", { fg = c.vscPopupFront, bg = c.vscBack })
	hl(0, "YankHighlight", { fg = c.vscWhite, bg = c.vscSplitDark })
	hl(0, "MatchParen", { fg = c.vscNone, bg = c.vscDimHighlight })
	hl(0, "ModeMsg", { fg = c.vscFront, bg = c.vscLeftDark })
	hl(0, "MoreMsg", { fg = c.vscFront, bg = c.vscLeftDark })
	hl(0, "NonText", { fg = (isDark and c.vscLineNumber or c.vscTabOther), bg = c.vscNone })
	hl(0, "Pmenu", { fg = isDark and c.vscPopupFront or "none", bg = c.vscPopupBack })
	hl(
		0,
		"PmenuSel",
		{ fg = isDark and c.vscPopupFront or "none", bg = isDark and c.vscPopupHighlightBlue or c.vscTabOutside }
	)
	hl(0, "PmenuSbar", { fg = "NONE", bg = c.vscPopupHighlightGray })
	hl(0, "PmenuThumb", { fg = "NONE", bg = c.vscPopupFront })
	hl(0, "Question", { fg = c.vscBlue, bg = c.vscBack })
	hl(0, "Search", { fg = c.vscNone, bg = c.vscSearch })
	hl(0, "SpecialKey", { fg = c.vscBlue, bg = c.vscNone })
	hl(0, "StatusLine", { fg = c.vscFront, bg = c.vscLeftMid })
	hl(0, "StatusLineNC", { fg = c.vscFront, bg = c.vscLeftDark })
	hl(0, "TabLine", { fg = c.vscFront, bg = c.vscTabOther })
	hl(0, "TabLineFill", { fg = c.vscFront, bg = c.vscTabOutside })
	hl(0, "TabLineSel", { fg = c.vscFront, bg = c.vscTabCurrent })
	hl(0, "Title", { fg = c.vscNone, bg = c.vscNone, bold = true })
	hl(0, "Visual", { fg = c.vscNone, bg = c.vscSelection })
	hl(0, "VisualNOS", { fg = c.vscNone, bg = c.vscSelection })
	hl(0, "WarningMsg", { fg = c.vscYellow, bg = c.vscBack })
	hl(0, "WildMenu", { fg = c.vscNone, bg = c.vscSelection })
	hl(0, "Comment", { fg = c.vscGreen, bg = "NONE", italic = false })
	hl(0, "Constant", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "String", { fg = c.vscOrange, bg = "NONE" })
	hl(0, "Character", { fg = c.vscOrange, bg = "NONE" })
	hl(0, "Number", { fg = c.vscLightGreen, bg = "NONE" })
	hl(0, "Boolean", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "Float", { fg = c.vscLightGreen, bg = "NONE" })
	hl(0, "Identifier", { fg = c.vscLightBlue, bg = "NONE" })
	hl(0, "Function", { fg = c.vscYellow, bg = "NONE" })
	hl(0, "Statement", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Conditional", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Repeat", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Label", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Operator", { fg = c.vscFront, bg = "NONE" })
	hl(0, "Keyword", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Exception", { fg = c.vscPink, bg = "NONE" })
	hl(0, "PreProc", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Include", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Define", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Macro", { fg = c.vscPink, bg = "NONE" })
	hl(0, "Type", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "StorageClass", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "Structure", { fg = c.vscBlueGreen, bg = "NONE" })
	hl(0, "Typedef", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "Special", { fg = c.vscYellowOrange, bg = "NONE" })
	hl(0, "SpecialChar", { fg = c.vscFront, bg = "NONE" })
	hl(0, "Tag", { fg = c.vscFront, bg = "NONE" })
	hl(0, "Delimiter", { fg = c.vscFront, bg = "NONE" })
	hl(0, "SpecialComment", { fg = c.vscGreen, bg = "NONE" })
	hl(0, "Debug", { fg = c.vscFront, bg = "NONE" })
	hl(0, "Underlined", { fg = c.vscNone, bg = "NONE", underline = true })
	hl(0, "Conceal", { fg = c.vscFront, bg = c.vscBack })
	hl(0, "Ignore", { fg = c.vscFront, bg = "NONE" })
	hl(0, "Error", { fg = c.vscRed, bg = c.vscBack, undercurl = true, sp = c.vscRed })
	hl(0, "Todo", { fg = c.vscYellowOrange, bg = c.vscBack, bold = true })
	hl(0, "SpellBad", { fg = "NONE", undercurl = true, sp = c.vscRed })
	hl(0, "SpellCap", { fg = "NONE", undercurl = true, sp = c.vscYellow })
	hl(0, "SpellRare", { fg = "NONE", undercurl = true, sp = c.vscViolet })
	hl(0, "SpellLocal", { fg = "NONE", undercurl = true, sp = c.vscBlue })
	hl(0, "Whitespace", { fg = isDark and c.vscLineNumber or c.vscTabOther })
	hl(0, "NormalFloat", { bg = c.vscPopupBack })
	hl(0, "WinBar", { fg = c.vscFront, bg = c.vscBack, bold = true })
	hl(0, "WinBarNc", { fg = c.vscFront, bg = c.vscBack })
	hl(0, "QuickFixLine", { bold = true })

	-- Treesitter
	hl(0, "@error", { fg = c.vscRed, bg = "NONE" }) -- Legacy
	hl(0, "@punctuation.bracket", { fg = c.vscPink, bg = "NONE" })
	hl(0, "@punctuation.special", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@punctuation.delimiter", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@comment", { fg = c.vscGreen, bg = "NONE", italic = false })
	hl(0, "@comment.note", { fg = c.vscBlueGreen, bg = "NONE", bold = true })
	hl(0, "@comment.warning", { fg = c.vscYellowOrange, bg = "NONE", bold = true })
	hl(0, "@comment.error", { fg = c.vscRed, bg = "NONE", bold = true })
	hl(0, "@constant", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@constant.builtin", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@constant.macro", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@string.regexp", { fg = c.vscOrange, bg = "NONE" })
	hl(0, "@string", { fg = c.vscOrange, bg = "NONE" })
	hl(0, "@character", { fg = c.vscOrange, bg = "NONE" })
	hl(0, "@number", { fg = c.vscLightGreen, bg = "NONE" })
	hl(0, "@number.float", { fg = c.vscLightGreen, bg = "NONE" })
	hl(0, "@boolean", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@annotation", { fg = c.vscYellow, bg = "NONE" })
	hl(0, "@attribute", { fg = c.vscYellow, bg = "NONE" })
	hl(0, "@attribute.builtin", { fg = c.vscBlueGreen, bg = "NONE" })
	hl(0, "@module", { fg = c.vscBlueGreen, bg = "NONE" })
	hl(0, "@function", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@function.builtin", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@function.macro", { fg = c.vscYellow, bg = "NONE" })
	hl(0, "@function.method", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@define", { fg = c.vscPink, bg = "NONE" })
	hl(0, "@variable", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@variable.builtin", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@variable.parameter", { fg = c.vscGray50, bg = "NONE" })
	hl(0, "@variable.parameter.reference", { fg = c.vscLightBlue, bg = "NONE" })
	hl(0, "@variable.member", { fg = c.vscGray83, bg = "NONE" })
	hl(0, "@property", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@constructor", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@label", { fg = c.vscChineseSilver, bg = "NONE" })
	hl(0, "@keyword", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@keyword.conditional", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@keyword.repeat", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@keyword.return", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@keyword.exception", { fg = c.vscPink, bg = "NONE" })
	hl(0, "@keyword.import", { fg = c.vscPink, bg = "NONE" })
	hl(0, "@operator", { fg = c.vscGray83, bg = "NONE" })
	hl(0, "@type", { fg = c.vscModerateCyan, bg = "NONE" })
	hl(0, "@type.builtin", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@type.qualifier", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@structure", { fg = c.vscLightBlue, bg = "NONE" })
	hl(0, "@tag", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@tag.builtin", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "@tag.delimiter", { fg = c.vscGray, bg = "NONE" })
	hl(0, "@tag.attribute", { fg = c.vscLightBlue, bg = "NONE" })

	hl(0, "@text", { fg = c.vscFront, bg = "NONE" }) -- Legacy
	hl(0, "@markup.strong", { fg = isDark and c.vscBlue or c.vscViolet, bold = true })
	hl(0, "@markup.italic", { fg = c.vscFront, bg = "NONE", italic = true })
	hl(0, "@markup.underline", { fg = c.vscYellowOrange, bg = "NONE", underline = true })
	hl(0, "@markup.strikethrough", { fg = c.vscFront, bg = "NONE", strikethrough = true })
	hl(0, "@markup.heading", { fg = isDark and c.vscBlue or c.vscYellowOrange, bold = true })
	hl(0, "@markup.heading.1.markdown", { fg = c.vscBlue, bg = "NONE", bold = true })
	hl(0, "@markup.heading.2.markdown", { fg = c.vscOrange, bg = "NONE", bold = true })
	hl(0, "@markup.heading.3.markdown", { fg = c.vscYellow, bg = "NONE", bold = true })
	hl(0, "@markup.heading.4.markdown", { fg = c.vscGreen, bg = "NONE", bold = true })
	hl(0, "@markup.heading.5.markdown", { fg = c.vscBlue, bg = "NONE", bold = true })
	hl(0, "@markup.heading.6.markdown", { fg = c.vscPink, bg = "NONE", bold = true })
	hl(0, "@markup.raw", { fg = c.vscFront, bg = "NONE" })
	hl(0, "@markup.raw.markdown", { fg = c.vscOrange, bg = "NONE" })
	hl(0, "@markup.raw.markdown_inline", { fg = c.vscOrange, bg = "NONE" })
	hl(0, "@markup.link.label", { fg = c.vscLightBlue, bg = "NONE", underline = true })
	hl(0, "@markup.link.url", { fg = c.vscFront, bg = "NONE", underline = true })
	hl(0, "@markup.list.checked", { link = "Todo" })
	hl(0, "@markup.list.unchecked", { link = "Todo" })
	hl(0, "@textReference", { fg = isDark and c.vscOrange or c.vscYellowOrange })
	hl(0, "@stringEscape", { fg = isDark and c.vscOrange or c.vscYellowOrange, bold = true })

	hl(0, "@diff.plus", { link = "DiffAdd" })
	hl(0, "@diff.minus", { link = "DiffDelete" })
	hl(0, "@diff.delta", { link = "DiffChange" })

	-- LSP semantic tokens
	hl(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
	hl(0, "@lsp.type.type", { link = "@type" })
	hl(0, "@lsp.type.typeParameter", { link = "@type" })
	hl(0, "@lsp.type.macro", { link = "@constant" })
	hl(0, "@lsp.type.enumMember", { link = "@constant" })
	hl(0, "@lsp.typemod.variable.readonly", { link = "@constant" })
	hl(0, "@lsp.typemod.property.readonly", { link = "@constant" })
	hl(0, "@lsp.typemod.variable.constant", { link = "@constant" })
	hl(0, "@lsp.type.member", { link = "@function" })
	hl(0, "@lsp.type.keyword", { link = "@keyword" })
	hl(0, "@lsp.typemod.keyword.controlFlow", { fg = c.vscPink, bg = "NONE" })
	hl(0, "@lsp.type.comment.c", { fg = c.vscDimHighlight, bg = "NONE" })
	hl(0, "@lsp.type.comment.cpp", { fg = c.vscDimHighlight, bg = "NONE" })
	hl(0, "@event", { link = "Identifier" })
	hl(0, "@interface", { link = "Identifier" })
	hl(0, "@modifier", { link = "Identifier" })
	hl(0, "@regexp", { fg = c.vscRed, bg = "NONE" })
	hl(0, "@decorator", { link = "Identifier" })

	-- LSP
	hl(0, "DiagnosticOk", { fg = c.vscBlueGreen, bg = "NONE" })
	hl(0, "DiagnosticError", { fg = c.vscRed, bg = "NONE" })
	hl(0, "DiagnosticWarn", { fg = c.vscYellow, bg = "NONE" })
	hl(0, "DiagnosticInfo", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "DiagnosticHint", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "DiagnosticUnnecessary", { fg = c.vscGray50, bg = "NONE", undercurl = true, sp = c.vscRed })
	hl(0, "DiagnosticUnderlineError", { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscRed })
	hl(0, "DiagnosticUnderlineWarn", { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscYellow })
	hl(0, "DiagnosticUnderlineInfo", { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscBlue })
	hl(0, "DiagnosticUnderlineHint", { fg = "NONE", bg = "NONE", undercurl = true, sp = c.vscBlue })

	hl(0, "LspReferenceText", { fg = "NONE", bg = isDark and c.vscPopupHighlightGray or c.vscPopupHighlightLightBlue })
	hl(0, "LspReferenceRead", { fg = "NONE", bg = isDark and c.vscPopupHighlightGray or c.vscPopupHighlightLightBlue })
	hl(0, "LspReferenceWrite", { fg = "NONE", bg = isDark and c.vscPopupHighlightGray or c.vscPopupHighlightLightBlue })
	hl(0, "LspInlayHint", { fg = c.vscSuggestion, bg = "NONE", italic = false })
	hl(0, "LspFloatWinNormal", { fg = c.vscFront, bg = "NONE" })
	hl(0, "LspFloatWinBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspInfoBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaHoverBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaSignatureHelpBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaCodeActionBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaDefPreviewBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspLinesDiagBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaRenameBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaBorderTitle", { fg = c.vscCursorDark, bg = "NONE" })
	hl(0, "LSPSagaDiagnosticTruncateLine", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaDiagnosticBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaDiagnosticBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaShTruncateLine", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaShTruncateLine", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaDocTruncateLine", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaRenameBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "LspSagaLspFinderBorder", { fg = c.vscLineNumber, bg = "NONE" })

	-- NerdTree
	hl(0, "NvimTreeRootFolder", { fg = c.vscFront, bg = "NONE", bold = true })
	hl(0, "NvimTreeGitDirty", { fg = c.vscYellow, bg = "NONE" })
	hl(0, "NvimTreeGitNew", { fg = c.vscGreen, bg = "NONE" })
	hl(0, "NvimTreeImageFile", { fg = c.vscViolet, bg = "NONE" })
	hl(0, "NvimTreeEmptyFolderName", { fg = c.vscGray, bg = "NONE" })
	hl(0, "NvimTreeFolderName", { fg = c.vscFront, bg = "NONE" })
	hl(0, "NvimTreeSpecialFile", { fg = c.vscPink, bg = "NONE", underline = true })
	hl(0, "NvimTreeNormal", { fg = c.vscFront, bg = c.vscBack })
	hl(0, "NvimTreeCursorLine", { fg = "NONE", bg = c.vscCursorDarkDark })
	hl(0, "NvimTreeVertSplit", { fg = c.vscSplitDark, bg = c.vscBack })
	hl(0, "NvimTreeEndOfBuffer", { fg = c.vscCursorDarkDark })
	hl(0, "NvimTreeOpenedFolderName", { fg = "NONE", bg = c.vscCursorDarkDark })
	hl(0, "NvimTreeGitRenamed", { fg = c.vscGitRenamed, bg = "NONE" })
	hl(0, "NvimTreeGitIgnored", { fg = c.vscGitIgnored, bg = "NONE" })
	hl(0, "NvimTreeGitDeleted", { fg = c.vscGitDeleted, bg = "NONE" })
	hl(0, "NvimTreeGitStaged", { fg = c.vscGitStageModified, bg = "NONE" })
	hl(0, "NvimTreeGitMerge", { fg = c.vscGitUntracked, bg = "NONE" })
	hl(0, "NvimTreeGitDirty", { fg = c.vscGitModified, bg = "NONE" })
	hl(0, "NvimTreeGitNew", { fg = c.vscGitAdded, bg = "NONE" })
	hl(0, "NvimTreeFolderIcon", { fg = c.vscBlue, bg = "NONE" })
	hl(0, "NvimTreeIndentMarker", { fg = c.vscLineNumber, bg = "NONE" })

	-- Telescope
	hl(0, "TelescopePromptBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "TelescopeResultsBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "TelescopePreviewBorder", { fg = c.vscLineNumber, bg = "NONE" })
	hl(0, "TelescopeNormal", { fg = c.vscFront, bg = "NONE" })
	hl(0, "TelescopeSelection", { fg = c.vscFront, bg = c.vscPopupHighlightBlue })
	hl(0, "TelescopeMultiSelection", { fg = c.vscFront, bg = c.vscPopupHighlightBlue })
	hl(0, "TelescopeMatching", { fg = c.vscMediumBlue, bg = "NONE", bold = true })
	hl(0, "TelescopePromptPrefix", { fg = c.vscFront, bg = "NONE" })

	-- Cmp
	hl(0, "CmpItemKindVariable", { fg = c.vscLightBlue, bg = "NONE" })
	hl(0, "CmpItemKindInterface", { fg = c.vscLightBlue, bg = "NONE" })
	hl(0, "CmpItemKindText", { fg = c.vscLightBlue, bg = "NONE" })
	hl(0, "CmpItemKindFunction", { fg = c.vscPink, bg = "NONE" })
	hl(0, "CmpItemKindMethod", { fg = c.vscPink, bg = "NONE" })
	hl(0, "CmpItemKindKeyword", { fg = c.vscFront, bg = "NONE" })
	hl(0, "CmpItemKindProperty", { fg = c.vscFront, bg = "NONE" })
	hl(0, "CmpItemKindUnit", { fg = c.vscFront, bg = "NONE" })
	hl(0, "CmpItemKindConstructor", { fg = c.vscUiOrange, bg = "NONE" })
	hl(0, "CmpItemMenu", { fg = c.vscPopupFront, bg = "NONE" })
	hl(0, "CmpItemAbbr", { fg = c.vscFront, bg = "NONE" })
	hl(0, "CmpItemAbbrDeprecated", { fg = c.vscCursorDark, bg = c.vscPopupBack, strikethrough = true })
	hl(0, "CmpItemAbbrMatch", { fg = isDark and c.vscMediumBlue or c.vscDarkBlue, bg = "NONE", bold = true })
	hl(0, "CmpItemAbbrMatchFuzzy", { fg = isDark and c.vscMediumBlue or c.vscDarkBlue, bg = "NONE", bold = true })
end

return M
